void entete();
void recupAddress(char *donnees);
void recupID(char *donnees, char *Address, char *MSR);
int recupMsr(int *IP);
int recupMsrCIDRforma(char *MSR, int *valide);
int* recupIP(char *Address, int *valid);
int* allocation(int size);
int* convertion(int chiffre);
int* puissance(int pow);
int reconversion(int *tab, int *fact);
int* netmaskRecup(int msr);
int* reversNetmaskRecup(int msr);
int nbHote(int msr);
int* addressReseau(int *IP, int *netmask);
int* addressDiffus(int *adresreseau, int *reversnetmask);
void verifCIDRforma();
void verif();
void display(int *IP, int *netmask, int nb_hote, int *adresreseau, int *adresdiffus);
